export const enum SOCKET_STRING {
    CONNECTION = 'connection',
    DISCONNECT = 'disconnect',
    //practice-office
    // PRACTICE_OFFICE_TYPING = 'practice-office-typing',
    // PRACTICE_OFFICE_STOP_TYPING = 'practice-office-stop-typing',
    // PRACTICE_OFFICE_TYPING_RESPONSE = 'practice-office-typingResponse',
    // PRACTICE_OFFICE_NEW_MESSAGE = 'practice-office-new-message',
    // PRACTICE_OFFICE_CHAT_HISTORY = 'practice-office-chat-history',
    // PRACTICE_OFFICE_STOP_TYPING_RESPONSE = 'practice-office-stop-typing-response',
    // PRACTICE_OFFICE_SET_ONLINE = 'practice-office-set-online',
    // PRACTICE_OFFICE_SET_OFFLINE = 'practice-office-set-offline',
    // PRACTICE_OFFICE_UPDATE_LAST_SEEN = 'practice-office-last-seen',
    // PRACTICE_OFFICE_NOTIFY = 'practice-office-notify',
    // PRACTICE_OFFICE_MESSAGE_DELETE = 'practice-office-message-delete',
    // PRACTICE_OFFICE_DELETED_MESSAGE = 'practice-office-deleted-message',
    // PRACTICE_OFFICE_JOIN_ROOM = 'practice-office-join-chat-room',
    // PRACTICE_OFFICE_ENTERED_ROOM = 'practice-office-entered-room',
    // PRACTICE_OFFICE_LIST_UPDATE_MESSAGE_COUNT = 'practice-office-list-update-message-count',
    // PRACTICE_OFFICE_READ_NEW_MESSAGE = 'practice-office-read-new-message',
    //practice-patient
    PRACTICE_OFFICE_TYPING = 'practice-office-typing',
    PRACTICE_OFFICE_STOP_TYPING = 'practice-office-stop-typing',
    PRACTICE_OFFICE_TYPING_RESPONSE = 'practice-office-typingResponse',
    PRACTICE_OFFICE_NEW_MESSAGE = 'practice-office-new-message',
    PRACTICE_OFFICE_CHAT_HISTORY = 'practice-office-chat-history',
    PRACTICE_OFFICE_STOP_TYPING_RESPONSE = 'practice-office-stop-typing-response',
    PRACTICE_OFFICE_SET_ONLINE = 'practice-office-set-online',
    PRACTICE_OFFICE_SET_OFFLINE = 'practice-office-set-offline',
    PRACTICE_OFFICE_UPDATE_LAST_SEEN = 'practice-office-last-seen',
    PRACTICE_OFFICE_NOTIFY = 'practice-office-notify',
    PRACTICE_OFFICE_MESSAGE_DELETE = 'practice-office-message-delete',
    PRACTICE_OFFICE_DELETED_MESSAGE = 'practice-office-deleted-message',
    PRACTICE_OFFICE_JOIN_ROOM = 'practice-office-join-chat-room',
    PRACTICE_OFFICE_ENTERED_ROOM = 'practice-office-entered-room',
    PRACTICE_OFFICE_LIST_UPDATE_MESSAGE_COUNT = 'practice-office-list-update-message-count',
    PRACTICE_OFFICE_READ_NEW_MESSAGE = 'practice-office-read-new-message',
    PRACTICE_OFFICE_ADD_ROOM = 'practice-office-add-room',
    PRACTICE_OFFICE_ADD_ROOM_NOTIFY = 'practice-office-add-room-notify',
    PRACTICE_OFFICE_UPDATE_ROOM_AFTER_ACCEPT_OR_REJECT = 'practice-office-update-room-after-accept-or-reject',
    PRACTICE_OFFICE_UPDATE_ROOM_ACCEPT_OR_REJECT_RESPONSE = 'practice-office-update-room-accept-or-reject-response',
}